name: Deploy content to Github Pages
on:
  workflow_dispatch:
concurrency:
  group: 'pages'
  cancel-in-progress: true
permissions:
  contents: read
  pages: write
  id-token: write
env:
  VITE_CAT_API_KEY: ${{ secrets.VITE_CAT_API_KEY }}
  VITE_CAT_API_URL: ${{ secrets.VITE_CAT_API_URL }}
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Setup environment
        run: |
          export VITE_CAT_API_KEY="${{ secrets.VITE_CAT_API_KEY }}"
          export VITE_CAT_API_URL="${{ secrets.VITE_CAT_API_URL }}"
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: only-frontend
      - name: Set up PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 9.15.2
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 22.9.0
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Build
        run: pnpm run build
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
